[options]
addons_path = source\odoo\addons,myaddons
server_wide_modules = base,web,app_common,app_odoo_customize
bin_path = runtime\win32\wkhtmltopdf
pg_path = runtime\pgsql\bin
data_dir = odoofile
db_host = 127.0.0.1
db_maxconn = 64
db_name = False
db_user = odoo
db_password = odoo
db_port = 5432
loglevel = warn
log_level = warn
db_template = template0
proxy_mode = True
http_port = 8018
xmlrpc_port = 8018
workers = False
max_cron_threads = 2
admin_passwd = $pbkdf2-sha512$600000$3pvTOgfA.D9HKAXgXIuRkg$C5kJUeLuIamBbUOmzfj3uO8wWQu4wK8t2R1wpA..1bpUNlQrKqOYGLfCK07OLVXQcgWIXZAv1n7QlkZ5kUea8w

limit_memory_hard = False
limit_memory_soft = False
limit_request = False
limit_time_cpu = False
limit_time_real = False
limit_time_real_cron = False
